name: Go Tests
on: [push, pull_request]
jobs:
  build-1_22:
    name: Build 1.22
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
          cache: false
        id: go
      - name: Disable cgo
        run: |
          echo "CGO_ENABLED=0" >> $GITHUB_ENV
      - name: Show version
        run: go version
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build
        run: go build -v .

  build-1_23:
    name: Build 1.23
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
          cache: false
        id: go
      - name: Disable cgo
        run: |
          echo "CGO_ENABLED=0" >> $GITHUB_ENV
      - name: Show version
        run: go version
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build
        run: go build -v .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
          cache: false
        id: go
      - name: Disable cgo
        run: |
          echo "CGO_ENABLED=0" >> $GITHUB_ENV
      - name: Show version
        run: go version
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -v ./...
